//! src/graphics/spritebatch.zig
//!
//! Append-streaming 2D sprite batcher.
//!
//! DESIGN (the anti-refactor decisions):
//!   * It does NOT own a pipeline. Each flush asks a shared PipelineCache for
//!     the pipeline matching its (shader, layout, index_type, pass, blend) key.
//!     Adding a deferred/offscreen pass = pass a different PassSignature to
//!     begin(); no batcher changes.
//!   * Vertices stream via sg.appendBuffer (callable many times per frame), so
//!     flushing N times per frame into ONE buffer is legal and stall-free —
//!     sokol rotates backing buffers internally.
//!   * The INDEX buffer is static/immutable: the quad pattern (0,1,2, 0,2,3)
//!     never changes, so it's baked once at init and reused by every flush.
//!     Index width honors the framework IndexType.
//!
//! In-batch flush triggers: texture change, and capacity reached. Blend / shader
//! / pass are fixed for a begin()..end() span (the MonoGame model) — change them
//! by ending and beginning again.
//!
//! GENERATED-SHADER SYMBOLS: the names below come from sokol-shdc's output for
//! shaders/sprite.glsl (program "sprite", uniform block "vs_params", texture
//! "tex", sampler "smp"). Confirm them against the generated sprite.glsl.zig —
//! in particular the texture *view* bind slot may be `VIEW_tex` or `IMG_tex`
//! depending on shdc version. If it differs, fix the one constant alias below.

const std = @import("std");
const sg = @import("sokol").gfx;
const zupra = @import("../root.zig");

const gfx = @import("../graphics/graphics.zig"); // IndexType (+ moved Vertex types)
const pipeline = @import("../graphics/pipeline.zig");
const tex = @import("../graphics/texture.zig");
const cam = @import("camera.zig");
const math = @import("../math.zig");

// Generated by sokol-shdc from shaders/sprite.glsl. Adjust path to match build.
const shd = @import("shaders").sprite;

const Vertex2D = gfx.Vertex2D;
const PipelineCache = pipeline.PipelineCache;
const PipelineKey = pipeline.PipelineKey;
const PassSignature = pipeline.PassSignature;
const BlendMode = pipeline.BlendMode;
const VertexLayout = pipeline.VertexLayout;
const IndexType = gfx.IndexType;
const Texture = tex.Texture;
const Sprite = tex.Sprite;
const Camera2D = cam.Camera2D;
const Matrix = math.Matrix;
const ShaderProgram = gfx.ShaderProgram;

// --- generated-symbol aliases (single place to fix if shdc names differ) ---
const SHADER_DESC = shd.spriteShaderDesc;
const UB_VS_PARAMS = shd.UB_vs_params;
const SLOT_TEX_VIEW = shd.VIEW_tex; // texture view bind slot
const SLOT_SAMPLER = shd.SMP_smp;
const VsParams = shd.VsParams; // extern struct { mvp: [16]f32 align(16) }

pub const SpriteBatchOptions = struct {
    /// Max quads buffered before a forced flush. With .u16 indices this must
    /// keep max vertex index (max_quads*4 - 1) within 65535 -> <= 16384.
    max_quads: u32 = 4096,
    index_type: IndexType = .u32,
    /// Texture filtering for the shared sampler.
    filter: sg.Filter = .LINEAR,
    wrap: sg.Wrap = .CLAMP_TO_EDGE,
    fs_uniform_capacity: usize = 256,
};

pub const SpriteBatch = struct {
    cache: *PipelineCache,

    vbuf: sg.Buffer, // streaming vertices
    ibuf: sg.Buffer, // static quad indices
    sampler: sg.Sampler,
    shader: ShaderProgram,

    cpu: []Vertex2D, // scratch for the current run
    max_quads: u32,
    index_type: IndexType,
    fs_scratch: []u8,
    fs_len: usize = 0,

    // begin()..end() state
    active: bool = false,
    mvp: Matrix = undefined,
    blend: BlendMode = .alpha,
    pass: PassSignature = PassSignature.swapchain,
    custom_shader: ?ShaderProgram = null,

    // current run
    quad_count: u32 = 0,
    cur_view: sg.View = .{},
    cur_view_valid: bool = false,

    pub fn init(allocator: std.mem.Allocator, cache: *PipelineCache, opts: SpriteBatchOptions) !SpriteBatch {
        // Validate capacity against index width.
        if (opts.index_type == .u16) {
            std.debug.assert(opts.max_quads * 4 <= 65536);
        }

        const vert_count = opts.max_quads * 4;
        const cpu = try allocator.alloc(Vertex2D, vert_count);
        errdefer allocator.free(cpu);

        // Streaming vertex buffer (no initial data).
        const vbuf = sg.makeBuffer(.{
            .size = vert_count * @sizeOf(Vertex2D),
            .usage = .{ .vertex_buffer = true, .stream_update = true },
        });

        // Static index buffer: bake the quad pattern once.
        const ibuf = try makeQuadIndexBuffer(allocator, opts.max_quads, opts.index_type);

        const sampler = sg.makeSampler(.{
            .min_filter = opts.filter,
            .mag_filter = opts.filter,
            .wrap_u = opts.wrap,
            .wrap_v = opts.wrap,
        });

        const shader = ShaderProgram.init(SHADER_DESC, .{ .slots = .{
            .tex_view = shd.VIEW_tex,
            .sampler = shd.SMP_smp,
            .vs_params = shd.UB_vs_params,
        } });

        const fs_scratch = try allocator.alloc(u8, opts.fs_uniform_capacity);
        errdefer allocator.free(fs_scratch);

        return .{
            .cache = cache,
            .vbuf = vbuf,
            .ibuf = ibuf,
            .sampler = sampler,
            .shader = shader,
            .cpu = cpu,
            .max_quads = opts.max_quads,
            .index_type = opts.index_type,
            .fs_scratch = fs_scratch,
        };
    }

    pub fn deinit(self: *SpriteBatch, allocator: std.mem.Allocator) void {
        self.shader.deinit();
        sg.destroySampler(self.sampler);
        sg.destroyBuffer(self.ibuf);
        sg.destroyBuffer(self.vbuf);
        allocator.free(self.cpu);
        allocator.free(self.fs_scratch);
    }

    /// Begin a batch. `blend` and any `shader` override apply to the whole span.
    /// `pass` defaults to the swapchain; pass an offscreen signature for FBO/MRT.
    pub fn begin(self: *SpriteBatch, camera: Camera2D, blend: BlendMode) void {
        self.beginEx(camera, blend, PassSignature.swapchain, null, null);
    }

    pub fn beginEx(
        self: *SpriteBatch,
        camera: Camera2D,
        blend: BlendMode,
        pass: PassSignature,
        custom_shader: ?ShaderProgram,
        fs_uniforms: ?[]const u8,
    ) void {
        std.debug.assert(!self.active);
        self.active = true;
        self.mvp = camera.viewProjection();
        self.blend = blend;
        self.pass = pass;
        self.custom_shader = custom_shader;
        self.quad_count = 0;
        self.cur_view_valid = false;

        // Copy so the caller's source (often a stack local) can die after begin().
        self.fs_len = 0;
        if (fs_uniforms) |bytes| {
            std.debug.assert(bytes.len <= self.fs_scratch.len); // else raise fs_uniform_capacity
            @memcpy(self.fs_scratch[0..bytes.len], bytes);
            self.fs_len = bytes.len;
        }
    }

    pub fn draw(self: *SpriteBatch, sprite: Sprite) void {
        std.debug.assert(self.active);
        const t = sprite.region.texture;

        // Flush trigger 1: texture change.
        if (self.cur_view_valid and self.cur_view.id != t.view.id) {
            self.flush();
        }
        // Flush trigger 2: capacity.
        if (self.quad_count == self.max_quads) {
            self.flush();
        }

        self.cur_view = t.view;
        self.cur_view_valid = true;

        self.writeQuad(sprite, t);
        self.quad_count += 1;
    }

    pub fn end(self: *SpriteBatch) void {
        std.debug.assert(self.active);
        self.flush();
        self.active = false;
    }

    // --- internals ---

    fn flush(self: *SpriteBatch) void {
        if (self.quad_count == 0) return;

        const vcount = self.quad_count * 4;
        const offset = sg.appendBuffer(self.vbuf, sg.asRange(self.cpu[0..vcount]));

        const prog = self.custom_shader orelse self.shader;

        const key = PipelineKey{
            .shader = prog.handle,
            .layout = prog.layout,
            .index_type = self.index_type,
            .pass = self.pass,
            .cull = .NONE,
            .blend = self.blend,
            .depth_test = false,
            .depth_write = false,
        };
        const pip = self.cache.get(key) catch |err| {
            std.log.err("SpriteBatch: pipeline cache failed: {}", .{err});
            self.quad_count = 0;
            return;
        };

        var bindings = sg.Bindings{};
        bindings.vertex_buffers[0] = self.vbuf;
        bindings.vertex_buffer_offsets[0] = offset;
        bindings.index_buffer = self.ibuf;
        bindings.views[prog.slots.tex_view] = self.cur_view;
        bindings.samplers[prog.slots.sampler] = self.sampler;

        var vs_params = VsParams{ .mvp = @bitCast(self.mvp) };

        sg.applyPipeline(pip);
        sg.applyBindings(bindings);
        sg.applyUniforms(prog.slots.vs_params, sg.asRange(&vs_params));
        if (self.fs_len > 0) {
            if (prog.slots.fs_params) |slot| {
                sg.applyUniforms(slot, sg.asRange(self.fs_scratch[0..self.fs_len]));
            }
        }
        sg.draw(0, self.quad_count * 6, 1);

        self.quad_count = 0;
    }

    fn writeQuad(self: *SpriteBatch, sprite: Sprite, t: Texture) void {
        const d = sprite.dest;
        const o = sprite.origin;
        const c = zupra.colors.packColorF(
            @floatCast(sprite.color.r),
            @floatCast(sprite.color.g),
            @floatCast(sprite.color.b),
            @floatCast(sprite.color.a),
        );

        // Local corners relative to origin (pixels), CCW from top-left.
        const corners = [4][2]f32{
            .{ 0 - o.x, 0 - o.y }, // top-left
            .{ d.width - o.x, 0 - o.y }, // top-right
            .{ d.width - o.x, d.height - o.y }, // bottom-right
            .{ 0 - o.x, d.height - o.y }, // bottom-left
        };

        const cos = @cos(sprite.rotation);
        const sin = @sin(sprite.rotation);

        // UVs from source rect, normalized; honor flips.
        const tw: f32 = @floatFromInt(t.width);
        const th: f32 = @floatFromInt(t.height);
        const s = sprite.region.source;
        var _u0 = s.x / tw;
        var _v0 = s.y / th;
        var _u1 = (s.x + s.width) / tw;
        var _v1 = (s.y + s.height) / th;
        if (sprite.flip_x) std.mem.swap(f32, &_u0, &_u1);
        if (sprite.flip_y) std.mem.swap(f32, &_v0, &_v1);
        const uvs = [4][2]f32{
            .{ _u0, _v0 }, .{ _u1, _v0 }, .{ _u1, _v1 }, .{ _u0, _v1 },
        };

        const base = self.quad_count * 4;
        inline for (0..4) |i| {
            const lx = corners[i][0];
            const ly = corners[i][1];
            // rotate then translate to dest position
            const rx = lx * cos - ly * sin + d.x;
            const ry = lx * sin + ly * cos + d.y;
            self.cpu[base + i] = .{ .pos = .{ rx, ry }, .uv = uvs[i], .color = c };
        }
    }
};

/// Build the immutable quad index buffer for `max_quads` quads in the chosen
/// width. Pattern per quad q (base = q*4): base+0,1,2, base+0,2,3.
fn makeQuadIndexBuffer(allocator: std.mem.Allocator, max_quads: u32, it: IndexType) !sg.Buffer {
    const index_count = max_quads * 6;
    switch (it) {
        .u16 => {
            const idx = try allocator.alloc(u16, index_count);
            defer allocator.free(idx);
            fillQuadIndices(u16, idx, max_quads);
            return sg.makeBuffer(.{
                .usage = .{ .index_buffer = true, .immutable = true },
                .data = sg.asRange(idx),
            });
        },
        .u32 => {
            const idx = try allocator.alloc(u32, index_count);
            defer allocator.free(idx);
            fillQuadIndices(u32, idx, max_quads);
            return sg.makeBuffer(.{
                .usage = .{ .index_buffer = true, .immutable = true },
                .data = sg.asRange(idx),
            });
        },
    }
}

fn fillQuadIndices(comptime T: type, out: []T, max_quads: u32) void {
    var q: u32 = 0;
    while (q < max_quads) : (q += 1) {
        const base: T = @intCast(q * 4);
        const o = q * 6;
        out[o + 0] = base + 0;
        out[o + 1] = base + 1;
        out[o + 2] = base + 2;
        out[o + 3] = base + 0;
        out[o + 4] = base + 2;
        out[o + 5] = base + 3;
    }
}
